spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doore
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: redirect-uri
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile

url:
  access-token: https://oauth2.googleapis.com/token
  profile: https://www.googleapis.com/userinfo/v2/me

jwt:
  secret-key: secret_key
  expire-length: 3_600_000_000
