name: Deploy BDD Production Server

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_SUBMODULE_TOKEN }}

      - name: AWS 자격증명 구성
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PROD_AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
